[package]
name = "arch-manwarn"
version = "0.8.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking", "rustls-tls"] }
tokio = { version = "1.46.1", features = ["full"] }
futures = "0.3.31"
feed-rs = "2.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
toml = "0.9.0"
html2text = "0.15.2"