[package]
name = "arch-manwarn"
version = "0.9.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.22", features = ["rustls-tls"] }
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
futures = "0.3.31"
feed-rs = "2.3.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
once_cell = "1.21.3"
toml = "0.9.1"
html2text = "0.15.2"